version: '3'
services:
  web:
    image: ruby:2.7
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: bash -c "bundle install && rake db:migrate && rails server -b 0.0.0.0"
    environment:
      - RACK_ENV=development
    networks:
      - webnet

networks:
  webnet:
