---
name: Run tests
on: pull-request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup and Run Tests
        run:  |
          docker-compose build
          docker-compose run web rake db:setup
          docker-compose run web rspec